[workspace]

resolver = "2"

members = [
    "crates/ibc",
]

exclude = [
    "ci/no-std-check",
]

[patch.crates-io]
ibc-proto = { git = "https://github.com/octopus-network/ibc-proto-rs.git", branch = "cosmos-sdk-v0.47.2-ibc-v7.0.0-for-vp" }
