[workspace]

resolver = "2"

members = [
    "crates/ibc",
    "crates/ibc-derive",
]

exclude = [
    "ci/no-std-check",
]

[patch.crates-io]
ibc-proto = { git = "https://github.com/octopus-network/ibc-proto-rs.git", branch = "full-cosmos-type-v0.32" }
